### ISSUE TITLE
projektidé

### ISSUE THREAD

**Issue by 1dv449** [hj222hi/1DV449-HJ222HI-Project#1]
"hjälp av google maps ta ut din position" - antar du menar att du ska använda geolocation plus att man kan ange städer via att integrera med karttjänsten? Annars ok, känns också som det finns plats för att kombinera med ytterligare data från städer om man vill, bilder, google places m.m.

**Comment by Jarleborn** [comment]
Ja men precis så! Håller med om att det verkligen finns plats för med, och jag tror det hade kunnat bli coolt om man gjorden så att bilder från staden läggs som ett collage i bakgrunden
